### ISSUE TITLE
behaviour.xar file is missing

### ISSUE THREAD

**Issue by MegasXLR001** [rouge555/solfege-ear-training-for-nao-robot-v2.1#1]
I downloaded all of .crg files. But when I open anyone, it says: "The project contains no behavior.xar file."

**Comment by rouge555** [comment]
hi,

all the crg files contains the behavior.xar file

this file is in the subdirectory solfegelearning when you open choregraphe

do you have the latest version of choregraphe 2.1, because it works only for the 2.1 version
if you have previous could be the reason

also it is better to import from choregraphe than open it , i found some bugs when opening directly

françois

**Comment by MegasXLR001** [comment]
I understood you, my choregraphe version is 1.14. I should update it. Thanks for information and help
